#!/usr/bin/env python3
"""
Installs the PennyTrace launcher icon into the Android project from the master PNGs in
assets/brand/ (run scripts/make-logo.py and scripts/render-logo.sh first).

  - adaptive icon (Android 8+): vector gradient background + PNG foreground at every density
  - legacy icons (square and round) at every density, for launchers that ignore adaptive icons

    python3 scripts/install-android-icons.py
"""
import pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / 'assets' / 'brand'
RES = ROOT / 'android' / 'app' / 'src' / 'main' / 'res'

DENSITIES = {'mdpi': 1.0, 'hdpi': 1.5, 'xhdpi': 2.0, 'xxhdpi': 3.0, 'xxxhdpi': 4.0}

def save(src, dest, size):
    img = Image.open(BRAND / src).convert('RGBA').resize((size, size), Image.LANCZOS)
    dest.parent.mkdir(parents=True, exist_ok=True)
    img.save(dest, optimize=True)

for name, scale in DENSITIES.items():
    save('adaptive-foreground-1024.png', RES / f'drawable-{name}' / 'ic_launcher_foreground.png', round(108 * scale))
    save('logo-rounded-1024.png', RES / f'mipmap-{name}' / 'ic_launcher.png', round(48 * scale))
    save('logo-round-1024.png', RES / f'mipmap-{name}' / 'ic_launcher_round.png', round(48 * scale))

# Gradient background as a vector: the app's hero gradient (140deg) plus the soft top-right glow.
(RES / 'drawable').mkdir(parents=True, exist_ok=True)
(RES / 'drawable' / 'ic_launcher_background.xml').write_text('''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/install-android-icons.py. App hero gradient: #1440DB, #2563FF, #4C95FF at 140deg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="19.3"
                android:startY="12.6"
                android:endX="88.7"
                android:endY="95.4">
                <item android:offset="0" android:color="#FF1440DB" />
                <item android:offset="0.52" android:color="#FF2563FF" />
                <item android:offset="1" android:color="#FF4C95FF" />
            </gradient>
        </aapt:attr>
    </path>
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="84.2"
                android:centerY="13"
                android:gradientRadius="59.4">
                <item android:offset="0" android:color="#4DFFFFFF" />
                <item android:offset="1" android:color="#00FFFFFF" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
''')

adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
'''
(RES / 'mipmap-anydpi-v26').mkdir(parents=True, exist_ok=True)
(RES / 'mipmap-anydpi-v26' / 'ic_launcher.xml').write_text(adaptive)
(RES / 'mipmap-anydpi-v26' / 'ic_launcher_round.xml').write_text(adaptive)
print('installed launcher icons into', RES.relative_to(ROOT))
